version: '3.1'

x-base:
  frontend: &base-frontend
    image: node:current-slim
    working_dir: /var/frontend
    volumes:
      - ./themes/guidonciniverdi:/var/frontend:z

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
      WP_ENVIRONMENT_TYPE: local
    volumes:
      - wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes:rw,z
      - ./plugins:/var/www/html/wp-content/plugins:rw,z
  
  frontend:
    <<: *base-frontend
    command: npm run dev
  
  frontend-reloader:
    <<: *base-frontend
    command: npm run start-sync-server
    ports:
      - 3000:3000
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin:latest
    tags: phpmyadmin
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 1G
    ports:
      - 8081:80
      
volumes:
  wordpress:
  db:
